require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
