default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contacomigo_development

test:
  <<: *default
  database: contacomigo_test

production:
  <<: *default
  database: contacomigo_production
  username: contacomigo
  password: <%= ENV["CONTACOMIGO_DATABASE_PASSWORD"] %>
